# Replace Roboto to Open Sans
REPLACE="
/system/fonts/Roboto-Black.ttf
/system/fonts/Roboto-BlackItalic.ttf
/system/fonts/Roboto-Bold.ttf
/system/fonts/Roboto-BoldItalic.ttf
/system/fonts/RobotoCondensed-Bold.ttf
/system/fonts/RobotoCondensed-BoldItalic.ttf
/system/fonts/RobotoCondensed-Italic.ttf
/system/fonts/RobotoCondensed-Light.ttf
/system/fonts/RobotoCondensed-LightItalic.ttf
/system/fonts/RobotoCondensed-Regular.ttf
/system/fonts/Roboto-Italic.ttf
/system/fonts/Roboto-Light.ttf
/system/fonts/Roboto-LightItalic.ttf
/system/fonts/Roboto-Medium.ttf
/system/fonts/Roboto-MediumItalic.ttf
/system/fonts/Roboto-Regular.ttf
/system/fonts/Roboto-Thin.ttf
/system/fonts/Roboto-ThinItalic.ttf
"